model:
  base_learning_rate: 5.0e-05
  target: bld.models.diffusion.bddpm.BinaryLatentDiffusion
  params:
    aux: 0.1
    linear_start: 0.00085
    linear_end: 1.0
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    #cond_stage_key: caption
    image_size: 32
    channels: 4
    #cond_stage_trainable: true
    #conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    unet_config:
      target: bld.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 1280
        use_checkpoint: true
        legacy: False

    first_stage_config:
      target: bld.models.bvae.BVAEModel
      params:
        embed_dim: 32
        n_embed: 1024
        monitor: val/rec_loss
        ckpt_path: logs/2023-10-24T08-41-06_bvae/checkpoints/last.ckpt
        ddconfig:
          double_z: False
          z_channels: 32
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__

    #TODO: add conditioning stage
    #cond_stage_config:
    #  target: bld.modules.encoders.modules.BERTEmbedder
    #  params:
    #    n_embed: 1280
    #    n_layer: 32

data: 
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    train:
      target: bld.data.custom.CustomTrain
      params:
        training_images_list_file: ./train.txt
        size: 256
    validation: 
      target: bld.data.custom.CustomTest
      params:
        test_images_list_file: ./val.txt
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True