model:
  base_learning_rate: 1.0e-6
  target: bld.models.bvae.BVAEModel
  params:
    emb_dim: 32
    codebook_size: 1024
    quantize: binary
    ddconfig:
      double_z: False
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,1,2,2,4] # num_down = len(ch_mult) - 1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: bld.modules.losses.perceptual.LPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.9

data: 
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    train:
      target: bld.data.custom.CustomTrain
      params:
        training_images_list_file: ./exp2.txt
        size: 256
    validation: 
      target: bld.data.custom.CustomTest
      params:
        test_images_list_file: ./exp2.txt
        size: 256